name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check appendix
        run: pwd
      - name: check dir
        run: ls
      - name: create appendix
        working-directory: ./sc23_appendices_template
        run: make
      - name: create appendix 2
        run: cd ./sc23_appendices_template && make
