name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Appendix_template.tex
          working_directory: ./sc23_appendices_template
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          working_directory: ./sc23_appendices_template
          path: Appendix_template.pdf
          
