name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check appendix
        run: pwd
      - name: check dir
        run: ls
      - name: create appendix
        run: make
